/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as BSlugRouteImport } from './routes/b.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminBoutiquesRouteImport } from './routes/_authenticated/admin.boutiques'
import { Route as AuthenticatedAdminCommercantsRouteImport } from './routes/_authenticated/admin.commercants'
import { Route as AuthenticatedAdminPaiementsRouteImport } from './routes/_authenticated/admin.paiements'
import { Route as AuthenticatedAdminParametresRouteImport } from './routes/_authenticated/admin.parametres'
import { Route as AuthenticatedAdminPlansRouteImport } from './routes/_authenticated/admin.plans'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardBoutiqueRouteImport } from './routes/_authenticated/dashboard.boutique'
import { Route as AuthenticatedDashboardCommandesRouteImport } from './routes/_authenticated/dashboard.commandes'
import { Route as AuthenticatedDashboardMetaRouteImport } from './routes/_authenticated/dashboard.meta'
import { Route as AuthenticatedDashboardProduitsRouteImport } from './routes/_authenticated/dashboard.produits'
import { Route as BSlugIndexRouteImport } from './routes/b.$slug.index'
import { Route as AuthenticatedAdminBoutiquesShopIdRouteImport } from './routes/_authenticated/admin.boutiques_.$shopId'
import { Route as AuthenticatedDashboardCommandesOrderIdRouteImport } from './routes/_authenticated/dashboard.commandes_.$orderId'
import { Route as ApiPublicMediaSplatRouteImport } from './routes/api/public/media/$'
import { Route as BSlugPProductIdRouteImport } from './routes/b.$slug.p.$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BSlugRoute = BSlugRouteImport.update({
  id: '/b/$slug',
  path: '/b/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminBoutiquesRoute =
  AuthenticatedAdminBoutiquesRouteImport.update({
    id: '/boutiques',
    path: '/boutiques',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCommercantsRoute =
  AuthenticatedAdminCommercantsRouteImport.update({
    id: '/commercants',
    path: '/commercants',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPaiementsRoute =
  AuthenticatedAdminPaiementsRouteImport.update({
    id: '/paiements',
    path: '/paiements',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminParametresRoute =
  AuthenticatedAdminParametresRouteImport.update({
    id: '/parametres',
    path: '/parametres',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPlansRoute = AuthenticatedAdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardBoutiqueRoute =
  AuthenticatedDashboardBoutiqueRouteImport.update({
    id: '/boutique',
    path: '/boutique',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCommandesRoute =
  AuthenticatedDashboardCommandesRouteImport.update({
    id: '/commandes',
    path: '/commandes',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMetaRoute =
  AuthenticatedDashboardMetaRouteImport.update({
    id: '/meta',
    path: '/meta',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProduitsRoute =
  AuthenticatedDashboardProduitsRouteImport.update({
    id: '/produits',
    path: '/produits',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const BSlugIndexRoute = BSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BSlugRoute,
} as any)
const AuthenticatedAdminBoutiquesShopIdRoute =
  AuthenticatedAdminBoutiquesShopIdRouteImport.update({
    id: '/boutiques_/$shopId',
    path: '/boutiques/$shopId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedDashboardCommandesOrderIdRoute =
  AuthenticatedDashboardCommandesOrderIdRouteImport.update({
    id: '/commandes_/$orderId',
    path: '/commandes/$orderId',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const ApiPublicMediaSplatRoute = ApiPublicMediaSplatRouteImport.update({
  id: '/api/public/media/$',
  path: '/api/public/media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BSlugPProductIdRoute = BSlugPProductIdRouteImport.update({
  id: '/p/$productId',
  path: '/p/$productId',
  getParentRoute: () => BSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/b/$slug': typeof BSlugRouteWithChildren
  '/admin/boutiques': typeof AuthenticatedAdminBoutiquesRoute
  '/admin/commercants': typeof AuthenticatedAdminCommercantsRoute
  '/admin/paiements': typeof AuthenticatedAdminPaiementsRoute
  '/admin/parametres': typeof AuthenticatedAdminParametresRoute
  '/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/dashboard/boutique': typeof AuthenticatedDashboardBoutiqueRoute
  '/dashboard/commandes': typeof AuthenticatedDashboardCommandesRoute
  '/dashboard/meta': typeof AuthenticatedDashboardMetaRoute
  '/dashboard/produits': typeof AuthenticatedDashboardProduitsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/b/$slug/': typeof BSlugIndexRoute
  '/admin/boutiques/$shopId': typeof AuthenticatedAdminBoutiquesShopIdRoute
  '/dashboard/commandes/$orderId': typeof AuthenticatedDashboardCommandesOrderIdRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/b/$slug/p/$productId': typeof BSlugPProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/admin/boutiques': typeof AuthenticatedAdminBoutiquesRoute
  '/admin/commercants': typeof AuthenticatedAdminCommercantsRoute
  '/admin/paiements': typeof AuthenticatedAdminPaiementsRoute
  '/admin/parametres': typeof AuthenticatedAdminParametresRoute
  '/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/dashboard/boutique': typeof AuthenticatedDashboardBoutiqueRoute
  '/dashboard/commandes': typeof AuthenticatedDashboardCommandesRoute
  '/dashboard/meta': typeof AuthenticatedDashboardMetaRoute
  '/dashboard/produits': typeof AuthenticatedDashboardProduitsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/b/$slug': typeof BSlugIndexRoute
  '/admin/boutiques/$shopId': typeof AuthenticatedAdminBoutiquesShopIdRoute
  '/dashboard/commandes/$orderId': typeof AuthenticatedDashboardCommandesOrderIdRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/b/$slug/p/$productId': typeof BSlugPProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/b/$slug': typeof BSlugRouteWithChildren
  '/_authenticated/admin/boutiques': typeof AuthenticatedAdminBoutiquesRoute
  '/_authenticated/admin/commercants': typeof AuthenticatedAdminCommercantsRoute
  '/_authenticated/admin/paiements': typeof AuthenticatedAdminPaiementsRoute
  '/_authenticated/admin/parametres': typeof AuthenticatedAdminParametresRoute
  '/_authenticated/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/_authenticated/dashboard/boutique': typeof AuthenticatedDashboardBoutiqueRoute
  '/_authenticated/dashboard/commandes': typeof AuthenticatedDashboardCommandesRoute
  '/_authenticated/dashboard/meta': typeof AuthenticatedDashboardMetaRoute
  '/_authenticated/dashboard/produits': typeof AuthenticatedDashboardProduitsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/b/$slug/': typeof BSlugIndexRoute
  '/_authenticated/admin/boutiques_/$shopId': typeof AuthenticatedAdminBoutiquesShopIdRoute
  '/_authenticated/dashboard/commandes_/$orderId': typeof AuthenticatedDashboardCommandesOrderIdRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/b/$slug/p/$productId': typeof BSlugPProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/terms'
    | '/admin'
    | '/dashboard'
    | '/onboarding'
    | '/b/$slug'
    | '/admin/boutiques'
    | '/admin/commercants'
    | '/admin/paiements'
    | '/admin/parametres'
    | '/admin/plans'
    | '/dashboard/boutique'
    | '/dashboard/commandes'
    | '/dashboard/meta'
    | '/dashboard/produits'
    | '/admin/'
    | '/dashboard/'
    | '/b/$slug/'
    | '/admin/boutiques/$shopId'
    | '/dashboard/commandes/$orderId'
    | '/api/public/media/$'
    | '/b/$slug/p/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/terms'
    | '/onboarding'
    | '/admin/boutiques'
    | '/admin/commercants'
    | '/admin/paiements'
    | '/admin/parametres'
    | '/admin/plans'
    | '/dashboard/boutique'
    | '/dashboard/commandes'
    | '/dashboard/meta'
    | '/dashboard/produits'
    | '/admin'
    | '/dashboard'
    | '/b/$slug'
    | '/admin/boutiques/$shopId'
    | '/dashboard/commandes/$orderId'
    | '/api/public/media/$'
    | '/b/$slug/p/$productId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/onboarding'
    | '/b/$slug'
    | '/_authenticated/admin/boutiques'
    | '/_authenticated/admin/commercants'
    | '/_authenticated/admin/paiements'
    | '/_authenticated/admin/parametres'
    | '/_authenticated/admin/plans'
    | '/_authenticated/dashboard/boutique'
    | '/_authenticated/dashboard/commandes'
    | '/_authenticated/dashboard/meta'
    | '/_authenticated/dashboard/produits'
    | '/_authenticated/admin/'
    | '/_authenticated/dashboard/'
    | '/b/$slug/'
    | '/_authenticated/admin/boutiques_/$shopId'
    | '/_authenticated/dashboard/commandes_/$orderId'
    | '/api/public/media/$'
    | '/b/$slug/p/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  BSlugRoute: typeof BSlugRouteWithChildren
  ApiPublicMediaSplatRoute: typeof ApiPublicMediaSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/b/$slug': {
      id: '/b/$slug'
      path: '/b/$slug'
      fullPath: '/b/$slug'
      preLoaderRoute: typeof BSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/boutiques': {
      id: '/_authenticated/admin/boutiques'
      path: '/boutiques'
      fullPath: '/admin/boutiques'
      preLoaderRoute: typeof AuthenticatedAdminBoutiquesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/commercants': {
      id: '/_authenticated/admin/commercants'
      path: '/commercants'
      fullPath: '/admin/commercants'
      preLoaderRoute: typeof AuthenticatedAdminCommercantsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/paiements': {
      id: '/_authenticated/admin/paiements'
      path: '/paiements'
      fullPath: '/admin/paiements'
      preLoaderRoute: typeof AuthenticatedAdminPaiementsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/parametres': {
      id: '/_authenticated/admin/parametres'
      path: '/parametres'
      fullPath: '/admin/parametres'
      preLoaderRoute: typeof AuthenticatedAdminParametresRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/plans': {
      id: '/_authenticated/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AuthenticatedAdminPlansRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/boutique': {
      id: '/_authenticated/dashboard/boutique'
      path: '/boutique'
      fullPath: '/dashboard/boutique'
      preLoaderRoute: typeof AuthenticatedDashboardBoutiqueRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/commandes': {
      id: '/_authenticated/dashboard/commandes'
      path: '/commandes'
      fullPath: '/dashboard/commandes'
      preLoaderRoute: typeof AuthenticatedDashboardCommandesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/meta': {
      id: '/_authenticated/dashboard/meta'
      path: '/meta'
      fullPath: '/dashboard/meta'
      preLoaderRoute: typeof AuthenticatedDashboardMetaRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/produits': {
      id: '/_authenticated/dashboard/produits'
      path: '/produits'
      fullPath: '/dashboard/produits'
      preLoaderRoute: typeof AuthenticatedDashboardProduitsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/b/$slug/': {
      id: '/b/$slug/'
      path: '/'
      fullPath: '/b/$slug/'
      preLoaderRoute: typeof BSlugIndexRouteImport
      parentRoute: typeof BSlugRoute
    }
    '/_authenticated/admin/boutiques_/$shopId': {
      id: '/_authenticated/admin/boutiques_/$shopId'
      path: '/boutiques/$shopId'
      fullPath: '/admin/boutiques/$shopId'
      preLoaderRoute: typeof AuthenticatedAdminBoutiquesShopIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/dashboard/commandes_/$orderId': {
      id: '/_authenticated/dashboard/commandes_/$orderId'
      path: '/commandes/$orderId'
      fullPath: '/dashboard/commandes/$orderId'
      preLoaderRoute: typeof AuthenticatedDashboardCommandesOrderIdRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/api/public/media/$': {
      id: '/api/public/media/$'
      path: '/api/public/media/$'
      fullPath: '/api/public/media/$'
      preLoaderRoute: typeof ApiPublicMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$slug/p/$productId': {
      id: '/b/$slug/p/$productId'
      path: '/p/$productId'
      fullPath: '/b/$slug/p/$productId'
      preLoaderRoute: typeof BSlugPProductIdRouteImport
      parentRoute: typeof BSlugRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBoutiquesRoute: typeof AuthenticatedAdminBoutiquesRoute
  AuthenticatedAdminCommercantsRoute: typeof AuthenticatedAdminCommercantsRoute
  AuthenticatedAdminPaiementsRoute: typeof AuthenticatedAdminPaiementsRoute
  AuthenticatedAdminParametresRoute: typeof AuthenticatedAdminParametresRoute
  AuthenticatedAdminPlansRoute: typeof AuthenticatedAdminPlansRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminBoutiquesShopIdRoute: typeof AuthenticatedAdminBoutiquesShopIdRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBoutiquesRoute: AuthenticatedAdminBoutiquesRoute,
  AuthenticatedAdminCommercantsRoute: AuthenticatedAdminCommercantsRoute,
  AuthenticatedAdminPaiementsRoute: AuthenticatedAdminPaiementsRoute,
  AuthenticatedAdminParametresRoute: AuthenticatedAdminParametresRoute,
  AuthenticatedAdminPlansRoute: AuthenticatedAdminPlansRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminBoutiquesShopIdRoute:
    AuthenticatedAdminBoutiquesShopIdRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardBoutiqueRoute: typeof AuthenticatedDashboardBoutiqueRoute
  AuthenticatedDashboardCommandesRoute: typeof AuthenticatedDashboardCommandesRoute
  AuthenticatedDashboardMetaRoute: typeof AuthenticatedDashboardMetaRoute
  AuthenticatedDashboardProduitsRoute: typeof AuthenticatedDashboardProduitsRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardCommandesOrderIdRoute: typeof AuthenticatedDashboardCommandesOrderIdRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardBoutiqueRoute: AuthenticatedDashboardBoutiqueRoute,
    AuthenticatedDashboardCommandesRoute: AuthenticatedDashboardCommandesRoute,
    AuthenticatedDashboardMetaRoute: AuthenticatedDashboardMetaRoute,
    AuthenticatedDashboardProduitsRoute: AuthenticatedDashboardProduitsRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardCommandesOrderIdRoute:
      AuthenticatedDashboardCommandesOrderIdRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BSlugRouteChildren {
  BSlugIndexRoute: typeof BSlugIndexRoute
  BSlugPProductIdRoute: typeof BSlugPProductIdRoute
}

const BSlugRouteChildren: BSlugRouteChildren = {
  BSlugIndexRoute: BSlugIndexRoute,
  BSlugPProductIdRoute: BSlugPProductIdRoute,
}

const BSlugRouteWithChildren = BSlugRoute._addFileChildren(BSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  BSlugRoute: BSlugRouteWithChildren,
  ApiPublicMediaSplatRoute: ApiPublicMediaSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
