/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as BSlugRouteImport } from './routes/b.$slug'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardBoutiqueRouteImport } from './routes/_authenticated/dashboard.boutique'
import { Route as AuthenticatedDashboardCommandesRouteImport } from './routes/_authenticated/dashboard.commandes'
import { Route as AuthenticatedDashboardProduitsRouteImport } from './routes/_authenticated/dashboard.produits'
import { Route as BSlugIndexRouteImport } from './routes/b.$slug.index'
import { Route as ApiPublicMediaSplatRouteImport } from './routes/api/public/media/$'
import { Route as BSlugPProductIdRouteImport } from './routes/b.$slug.p.$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BSlugRoute = BSlugRouteImport.update({
  id: '/b/$slug',
  path: '/b/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardBoutiqueRoute =
  AuthenticatedDashboardBoutiqueRouteImport.update({
    id: '/boutique',
    path: '/boutique',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCommandesRoute =
  AuthenticatedDashboardCommandesRouteImport.update({
    id: '/commandes',
    path: '/commandes',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProduitsRoute =
  AuthenticatedDashboardProduitsRouteImport.update({
    id: '/produits',
    path: '/produits',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const BSlugIndexRoute = BSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BSlugRoute,
} as any)
const ApiPublicMediaSplatRoute = ApiPublicMediaSplatRouteImport.update({
  id: '/api/public/media/$',
  path: '/api/public/media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BSlugPProductIdRoute = BSlugPProductIdRouteImport.update({
  id: '/p/$productId',
  path: '/p/$productId',
  getParentRoute: () => BSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/b/$slug': typeof BSlugRouteWithChildren
  '/dashboard/boutique': typeof AuthenticatedDashboardBoutiqueRoute
  '/dashboard/commandes': typeof AuthenticatedDashboardCommandesRoute
  '/dashboard/produits': typeof AuthenticatedDashboardProduitsRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/b/$slug/': typeof BSlugIndexRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/b/$slug/p/$productId': typeof BSlugPProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/dashboard/boutique': typeof AuthenticatedDashboardBoutiqueRoute
  '/dashboard/commandes': typeof AuthenticatedDashboardCommandesRoute
  '/dashboard/produits': typeof AuthenticatedDashboardProduitsRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/b/$slug': typeof BSlugIndexRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/b/$slug/p/$productId': typeof BSlugPProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/b/$slug': typeof BSlugRouteWithChildren
  '/_authenticated/dashboard/boutique': typeof AuthenticatedDashboardBoutiqueRoute
  '/_authenticated/dashboard/commandes': typeof AuthenticatedDashboardCommandesRoute
  '/_authenticated/dashboard/produits': typeof AuthenticatedDashboardProduitsRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/b/$slug/': typeof BSlugIndexRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/b/$slug/p/$productId': typeof BSlugPProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/onboarding'
    | '/b/$slug'
    | '/dashboard/boutique'
    | '/dashboard/commandes'
    | '/dashboard/produits'
    | '/dashboard/'
    | '/b/$slug/'
    | '/api/public/media/$'
    | '/b/$slug/p/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/onboarding'
    | '/dashboard/boutique'
    | '/dashboard/commandes'
    | '/dashboard/produits'
    | '/dashboard'
    | '/b/$slug'
    | '/api/public/media/$'
    | '/b/$slug/p/$productId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/dashboard'
    | '/_authenticated/onboarding'
    | '/b/$slug'
    | '/_authenticated/dashboard/boutique'
    | '/_authenticated/dashboard/commandes'
    | '/_authenticated/dashboard/produits'
    | '/_authenticated/dashboard/'
    | '/b/$slug/'
    | '/api/public/media/$'
    | '/b/$slug/p/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  BSlugRoute: typeof BSlugRouteWithChildren
  ApiPublicMediaSplatRoute: typeof ApiPublicMediaSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/b/$slug': {
      id: '/b/$slug'
      path: '/b/$slug'
      fullPath: '/b/$slug'
      preLoaderRoute: typeof BSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/boutique': {
      id: '/_authenticated/dashboard/boutique'
      path: '/boutique'
      fullPath: '/dashboard/boutique'
      preLoaderRoute: typeof AuthenticatedDashboardBoutiqueRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/commandes': {
      id: '/_authenticated/dashboard/commandes'
      path: '/commandes'
      fullPath: '/dashboard/commandes'
      preLoaderRoute: typeof AuthenticatedDashboardCommandesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/produits': {
      id: '/_authenticated/dashboard/produits'
      path: '/produits'
      fullPath: '/dashboard/produits'
      preLoaderRoute: typeof AuthenticatedDashboardProduitsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/b/$slug/': {
      id: '/b/$slug/'
      path: '/'
      fullPath: '/b/$slug/'
      preLoaderRoute: typeof BSlugIndexRouteImport
      parentRoute: typeof BSlugRoute
    }
    '/api/public/media/$': {
      id: '/api/public/media/$'
      path: '/api/public/media/$'
      fullPath: '/api/public/media/$'
      preLoaderRoute: typeof ApiPublicMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$slug/p/$productId': {
      id: '/b/$slug/p/$productId'
      path: '/p/$productId'
      fullPath: '/b/$slug/p/$productId'
      preLoaderRoute: typeof BSlugPProductIdRouteImport
      parentRoute: typeof BSlugRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardBoutiqueRoute: typeof AuthenticatedDashboardBoutiqueRoute
  AuthenticatedDashboardCommandesRoute: typeof AuthenticatedDashboardCommandesRoute
  AuthenticatedDashboardProduitsRoute: typeof AuthenticatedDashboardProduitsRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardBoutiqueRoute: AuthenticatedDashboardBoutiqueRoute,
    AuthenticatedDashboardCommandesRoute: AuthenticatedDashboardCommandesRoute,
    AuthenticatedDashboardProduitsRoute: AuthenticatedDashboardProduitsRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BSlugRouteChildren {
  BSlugIndexRoute: typeof BSlugIndexRoute
  BSlugPProductIdRoute: typeof BSlugPProductIdRoute
}

const BSlugRouteChildren: BSlugRouteChildren = {
  BSlugIndexRoute: BSlugIndexRoute,
  BSlugPProductIdRoute: BSlugPProductIdRoute,
}

const BSlugRouteWithChildren = BSlugRoute._addFileChildren(BSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  BSlugRoute: BSlugRouteWithChildren,
  ApiPublicMediaSplatRoute: ApiPublicMediaSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
